{
 "title": "Sentinel Operational Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total Events Ingested",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sentinel_events_ingested_total)"
    }
   ]
  },
  {
   "title": "Total Detections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sentinel_detections_fired_total)"
    }
   ]
  },
  {
   "title": "Queue Depth",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sentinel_queue_depth" }
   ]
  },
  {
   "title": "Ingestion Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(sentinel_events_ingested_total[1m])",
     "legendFormat": "Events / sec"
    }
   ]
  },
  {
   "title": "Detections Fired",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "increase(sentinel_detections_fired_total[1m])",
     "legendFormat": "{{rule_id}} (Sev: {{severity}})"
    }
   ]
  }
 ]
}