#!/usr/bin/env python3
"""Generate ``docs/COVERAGE.md`` — the detection rule -> framework matrix.

Loads the rule library and emits a Markdown table mapping every rule to its
MITRE ATT&CK techniques, NIST CSF 2.0 categories, and D3FEND countermeasures.
Run from the repo root: ``python scripts/generate_coverage_matrix.py``.
"""

from __future__ import annotations

from pathlib import Path

from sentinel.detection.loader import load_rules

_ROOT = Path(__file__).resolve().parent.parent


def render() -> str:
    """Render the coverage matrix as Markdown."""
    rules = sorted(load_rules(_ROOT / "rules"), key=lambda rule: rule.id)
    lines = [
        "# Detection coverage matrix",
        "",
        "<!-- Generated by scripts/generate_coverage_matrix.py — do not edit by hand. -->",
        "",
        f"**{len(rules)} detection rules.** Every rule maps to MITRE ATT&CK and NIST CSF 2.0, "
        "and carries a positive and a negative test enforced by "
        "`tests/test_detection_rules.py` (the library cannot grow an untested rule).",
        "",
        "| Rule | Sev | MITRE ATT&CK | NIST CSF 2.0 | D3FEND | Tests |",
        "| ---- | --- | ------------ | ------------ | ------ | ----- |",
    ]
    for rule in rules:
        attack = ", ".join(rule.attack)
        nist = ", ".join(rule.nist_csf)
        d3fend = ", ".join(rule.d3fend) or "—"
        lines.append(f"| `{rule.id}` | {rule.severity} | {attack} | {nist} | {d3fend} | ✅ |")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    output = _ROOT / "docs" / "COVERAGE.md"
    output.write_text(render(), encoding="utf-8")
    print(f"wrote {output.relative_to(_ROOT)} with {render().count('| `')} rules")


if __name__ == "__main__":
    main()
